@startuml

skinparam componentStyle uml2

package Preparacion {
	package "'PreparacionArchivosDiagnostico' Aggregate" <<Rectangle>> {
		class ArchivoAnonimizado <<(E,DarkSeaGreen) Entity>> {
		}
		class DatosAnonimizados <<(E,#ff9f4b) Domain Event>> {
		}
	}
}


@enduml
