@startuml

skinparam componentStyle uml2

package Verificacion {
	package "'VerificacionArchivosAnonimizados' Aggregate" <<Rectangle>> {
		class ArchivoAnonimizadoVerificacion <<(E,DarkSeaGreen) Entity>> {
		}
		class DatosVerificados <<(E,#ff9f4b) Domain Event>> {
		}
	}
}


@enduml
