@startuml

skinparam componentStyle uml2

package RegistroCuenta {
	package "'RegistroCuenta' Aggregate" <<Rectangle>> {
		class Cuenta <<(E,DarkSeaGreen) Entity>> {
		}
		class CuentaRegistrada <<(E,#ff9f4b) Domain Event>> {
		}
	}
}


@enduml
