@startuml

skinparam componentStyle uml2

package Automatizacion {
	package "'EjecucionAutomatizadaParaEntrenarModelo' Aggregate" <<Rectangle>> {
		class ProcesamientoFinalizado <<(E,#ff9f4b) Domain Event>> {
		}
		class DatosPersistidos <<(E,#ff9f4b) Domain Event>> {
		}
	}
}


@enduml
